### ISSUE TITLE
Add a command for deleting challenge channels

### ISSUE THREAD

**Issue by mklarz** [ekofiskctf/fiskebot#9]
People sometimes create a new channel for a challenge that already has a channel, there is no way to remove the newly challenge channel and thus has to be marked as "done" instead. Add a command for deleting a challenge channel, perhaps with a confirmation (i.e. have to type the channel name).

**Comment by gigglearrows** [comment]
!ctf delete <challenge> is already a thing. But seems to be a bug there. ref #7

**Comment by mklarz** [comment]
Closing this then
